### ISSUE TITLE
Question: state of the library

### ISSUE THREAD

**Issue by Goldziher** [adamdubicki/typeorm-entity-factory#25]
Hi @adamdubicki ,

This looks like an interesting and very useful project. Is it currently maintained?  I would love to use it - but I am a bit apprehensive seeing open PRs and issues. I would also be happy to contribute.

**Comment by adamdubicki** [comment]
Thank you for reaching out! I am currently not maintaining it. That repository is on hiatus. It has been a long time since someone has asked about the library - I will add a note about this to the repository. I may return to it once things come back to normal.
