### ISSUE TITLE
ReadMe Typos/clarity

### ISSUE THREAD

**Issue by michel-fresh** [adamdubicki/typeorm-entity-factory#4]
"Using _what we our previous factories_ -we can declare the last factory."
- Not sure what is intended here

"This will inject the database connection _into all of factories_"
- all factories?

"Each factory comes with a faker instance injected into it for creating random data."
- Consider rewording: "Each factory has an instance of faker". And it may make sense to link to faker.js repo for reference, or somehow acknowledge this is a package dependency. I wasn't sure what faker was on first read.

**Comment by adamdubicki** [comment]
Good catch - will update README in 0.0.10.
