### ISSUE TITLE
Husky failed to install

### ISSUE THREAD

**Issue by michel-fresh** [adamdubicki/typeorm-entity-factory#5]
After a `git clone`, `cd typeorm-entity-factory` and `docker-compose up -d`
```
> husky@4.2.3 install /usr/src/node_modules/husky
> node husky install

husky > Setting up git hooks
Cannot read property 'toString' of null
husky > Failed to install

> husky@4.2.3 postinstall /usr/src/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate
```

Maybe this is expected, I'm not familiar with Husky.

**Comment by adamdubicki** [comment]
https://github.com/typicode/husky/issues/655

Husky expects a git path - which I don't map within the volume. I believe this is fine as husky runs hooks on any commits outside the container - which is expected as there is git CLI inside the container. 

I will add this as part of the README in version 0.0.10.
