### ISSUE TITLE
Running nestjs: example cannot GET to '/'

### ISSUE THREAD

**Issue by michel-fresh** [adamdubicki/typeorm-entity-factory#6]
**Steps**

After git clone:

`cd typeorm-entity-factory/examples/nestjs`
`docker-compose up`
new terminal tab (maybe consider adding the -it flags in README)
`npm i`
`npm start`

**Issues:**
navigating to localhost:3000:
`{"statusCode":404,"error":"Not Found","message":"Cannot GET /"}`

navigating to `localhost:3000/users` returns an empty array

I assume the latter is expected but I wasn't clear how to use the package to generate user data in the db. Albeit I know very little about nest!

**Comment by adamdubicki** [comment]
There is a README within the root of the nestJS. The actual functionality of the package is used within the user's test for generating data.

I will add a mention to the README at the root of nest repo to use the command `npm run test`.

**Comment by michel-fresh** [comment]
Oh yeah totally, funny, I actually opened that readme but got distracted by the steps further down and glossed over the first few lines after the **NOTE**
